### ISSUE TITLE
run_common parameters

### ISSUE THREAD

**Issue by varhub** [ojgarciab/docker-gazebo-5#3]
_[Question]_
At run_common.sh:18, -u and -w should be $USER and $HOME?
What means both parameters?

**Comment by ojgarciab** [comment]
Yes, in my local repository that parameters are changed, but I didn't commited it.

Same for /dev directory, finally I mounted it, not individual device files or directories (like dri, nvidia, ect).

And finally sometimes, when I close gazebo, shows this message: "boost thread: trying joining itself: Resource deadlock avoided" and sometimes it keeps in background as zombi using 100% of one of the CPUs. I think that something is not working fine inside gazebo or using docker.

I'll do a quick commit right now, thanks.

**Comment by ojgarciab** [comment]
Fixed.

Thanks for the tip.

**Comment by varhub** [comment]
Dont worry.
I just was interested because seems that you enabled hardware acceleration.
If Docker uses debootstrap this is very tricky and overcome it is a great success. Specially for me due Bumblebee.
By now my only option is aufs layering.

**Comment by ojgarciab** [comment]
You can run bumblebee inside docker as you can see in this video:

https://www.youtube.com/watch?v=O-3yLK0E5Z8

You need to add optimus support inside `Dokerfile.in`:
https://github.com/ojgarciab/docker3d/blob/master/Dockerfile#L31

And then run gazebo prefixing it with `optirun gazebo` inside a shell, or modifying `run_gazebo.sh` script.
